name: ccvc_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dart
  dartx: ^0.7.1
  flutter_html: ^2.1.1
  auto_size_text: ^3.0.0-nullsafety.0
  optimized_cached_image: ^3.0.0

  #Favourite library
  share: ^2.0.1
  provider: ^5.0.0
  device_info: 2.0.0
  flutter_bloc: ^7.0.0
  package_info: ^2.0.0
  google_fonts: 2.0.0
  connectivity: ^3.0.3
  url_launcher: ^6.0.5
  path_provider: ^2.0.1
  webview_flutter: ^2.0.10
  shared_preferences: ^2.0.5
  lint: ^1.6.0
  table_calendar: ^3.0.2
  image_picker: ^0.8.4+3
  syncfusion_flutter_charts: ^19.4.38
  flutter_rounded_date_picker: ^2.0.2
  syncfusion_flutter_calendar: ^19.4.40
  date_format: ^2.0.2
  pin_code_fields: ^7.3.0
  keyboard_dismisser: ^2.0.0
  sticky_headers: ^0.2.0
  #Library helpful
  intl: ^0.17.0
  event_bus: ^2.0.0
  equatable: ^2.0.0
  fluttertoast: 8.0.3
  retrofit: ^2.0.1
  json_annotation: ^4.0.1
  flutter_screenutil: 5.0.0
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  logger: any
  rxdart: ^0.27.1
  hive: ^2.0.5

  #  permission_handler: ^8.1.4+2
  file_picker: ^4.0.2
  cool_alert: ^1.1.0
  expandable: 5.0.1
  queue: ^3.1.0+1

  dots_indicator: ^2.0.0
  dotted_border:
  #svg
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  dart_ipify: ^1.1.0

  # GET
  get: ^4.1.4
  pretty_dio_logger: ^1.1.1

  injectable: ^1.4.1
  freezed: ^0.14.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  hive_generator:
  build_runner:  #flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^4.1.0
  injectable_generator: ^1.4.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/menu/
    - assets/style/
flutter_intl:
  enabled: true
